# Auto-generated by defective_coin.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid
set logscale x
set xlabel 'n (number of coins)'
set ylabel 'number of weighings'
set output 'weighings.png'
set title 'Defective coin search: weighings vs n'

$DATA << EOD
# n max_weighings_with_defect max_weighings_no_defect ceil_log2n_plus_1
2 1 1 2.00
3 2 2 3.00
4 2 1 3.00
5 2 2 4.00
7 3 2 4.00
8 3 1 4.00
16 4 1 5.00
17 4 2 6.00
32 5 1 6.00
33 5 2 7.00
64 6 1 7.00
100 7 1 8.00
128 7 1 8.00
250 8 1 9.00
256 8 1 9.00
500 9 1 10.00
512 9 1 10.00
777 10 2 11.00
1000 10 1 11.00
1024 10 1 11.00
4096 12 1 13.00
12345 14 2 15.00
16384 14 1 15.00
65536 16 1 17.00
100000 17 1 18.00
262144 18 1 19.00
EOD

plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'worst-case weighings (defect present)', \
     $DATA using 1:3 with linespoints pt 5 lw 2 title 'worst-case weighings (no defect)', \
     $DATA using 1:4 with lines dt 2 lw 1.5 lc rgb 'red' title 'ceil(log2 n) + 1 (theoretical bound)'
