# Auto-generated by special_pattern_matmul.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid
set logscale xy

$DATA << EOD
# n dc_mults dc_adds dc_total naive_mults n_log2_3 n_squared n_cubed
2 3 5 8 8 3.00 4.00 8.00
4 9 35 44 64 9.00 16.00 64.00
8 27 185 212 512 27.00 64.00 512.00
16 81 875 956 4096 81.00 256.00 4096.00
32 243 3905 4148 32768 243.00 1024.00 32768.00
64 729 16835 17564 262144 729.00 4096.00 262144.00
128 2187 70985 73172 2097152 2187.00 16384.00 2097152.00
256 6561 294875 301436 16777216 6561.00 65536.00 16777216.00
512 19683 1212305 1231988 134217728 19683.00 262144.00 134217728.00
EOD

set output 'mults.png'
set title 'Special-pattern D&C: scalar MULTIPLICATIONS alone grow as n^log2(3)'
set xlabel 'n (matrix size)'
set ylabel 'count'
plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'D&C multiplications (measured)', \
     $DATA using 1:6 with lines dt 2 lw 1.5 lc rgb 'red' title 'n^log2(3) (theory)', \
     $DATA using 1:7 with lines dt 3 lw 1.5 lc rgb 'gray40' title 'n^2 (reference)'

set output 'totalops.png'
set title 'Special-pattern D&C (Theta(n^2)) vs Naive (Theta(n^3))'
set xlabel 'n (matrix size)'
set ylabel 'total elementary operations'
plot $DATA using 1:4 with linespoints pt 7 lw 2 title 'D&C total ops (mults+adds, measured)', \
     $DATA using 1:5 with linespoints pt 5 lw 2 title 'Naive multiplications (measured, = n^3)', \
     $DATA using 1:7 with lines dt 2 lw 1.5 lc rgb 'red'  title 'n^2 (theory, D&C)', \
     $DATA using 1:8 with lines dt 2 lw 1.5 lc rgb 'blue' title 'n^3 (theory, naive)'
