# Auto-generated by binary_vs_ternary.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid

$DATA << EOD
# n binary_cmp ternary_cmp binary_time ternary_time ratio log2n
1000 19.955998 23.987951 0.000000172 0.000000157 1.202042 9.965784
4000 23.952991 28.815018 0.000000227 0.000000257 1.202982 11.965784
16000 27.952248 32.952925 0.000000261 0.000000305 1.178901 13.965784
64000 31.952063 37.254313 0.000000317 0.000000360 1.165944 15.965784
256000 35.952017 42.540814 0.000000420 0.000000472 1.183266 17.965784
1024000 39.952002 47.348235 0.000000537 0.000000538 1.185128 19.965784
4096000 43.951999 51.250045 0.000000914 0.000000948 1.166046 21.965784
16384000 47.951999 55.931790 0.000001061 0.000001044 1.166412 23.965784
65536000 51.951999 61.040006 0.000001387 0.000001309 1.174931 25.965784
EOD

set output 'comparisons.png'
set title 'Binary vs Ternary Search: comparisons vs n (worst case)'
set xlabel 'n (array size)'
set ylabel 'average comparisons per search'
set logscale x
plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'Binary search', \
     $DATA using 1:3 with linespoints pt 5 lw 2 title 'Ternary search', \
     $DATA using 1:7 with lines dt 2 lw 1 lc rgb 'gray50' title 'log2(n) reference'

set output 'time.png'
set title 'Binary vs Ternary Search: time per search vs n (worst case)'
set xlabel 'n (array size)'
set ylabel 'average time per search (seconds)'
set logscale x
plot $DATA using 1:4 with linespoints pt 7 lw 2 title 'Binary search', \
     $DATA using 1:5 with linespoints pt 5 lw 2 title 'Ternary search'

set output 'ratio.png'
set title 'Ternary/Binary comparison ratio -- converges near 2/log2(3) = 1.262'
set xlabel 'n (array size)'
set ylabel 'ternary comparisons / binary comparisons'
set logscale x
set yrange [0.8:1.6]
set arrow from graph 0, first 1.2618595 to graph 1, first 1.2618595 nohead dt 2 lc rgb 'red'
plot $DATA using 1:6 with linespoints pt 7 lw 2 title 'measured ratio', \
     1.2618595 with lines dt 2 lw 1 lc rgb 'red' title '2/log2(3) (theory)'
